site_name: Daily Notes
site_url: https://baaghinitesh.github.io/dailly-notes/
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

# Automatically include all markdown files
nav:
  - Home: index.md
  - Instructions: instructions.md
  - DSA: 
      - 'docs/dsa'
  - Notes:
      - 'docs/notes'

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

# Plugins to show directories automatically
plugins:
  - search
  - awesome_pages
