site_name: Daily Notes
site_url: https://baaghinitesh.github.io/dailly-notes/
theme:
  name: material

nav:
  - Home: index.md
  - Instructions: instructions.md
  - DSA:
      - index: dsa/index.md
  - Notes:
      - index: notes/index.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
